### ISSUE TITLE
Unable to add package [https://github.com/GoCarrot/upm-package-teak.git]

### ISSUE THREAD

**Issue by psstevenchan** [GoCarrot/upm-package-teak#1]
Cannot perform upm operation: Unable to add package [https://github.com/GoCarrot/upm-package-teak.git]:
  Manifest [C:\Users\schan\Projects\mx-client-master_2019_lts\Slots\unity\Library\PackageCache\io.teak.unity.sdk@d23a2d4ae2\package.json] is invalid:
    Version '3.3.0.rc0-35-g2c9b65e' is invalid. Expected a 'SemVer' compatible value. [NotFound]

**Comment by ZeroStride** [comment]
Fixed for 4.0.0
