### ISSUE TITLE
Create branch to always get the latest version

### ISSUE THREAD

**Issue by AlexSc** [GoCarrot/upm-package-teak#2]
Currently the [doc page](https://docs.teak.io/unity/latest/upm.html) implies that `main` will always have the latest version, but then retracts that and says `main` only contains the code to build versions.

Perhaps `main` should be made what the doc first says, and a different branch should be created to contain the minimal code to build versions?

**Comment by AlexSc** [comment]
Alternate: Change the default branch to the latest major version (currently `4`). I just don't know what that does to CI.

**Comment by ZeroStride** [comment]
This is fixed in https://github.com/GoCarrot/teak-unity/commit/0534353a697ab5b31add0697877f03c1c391214f
